### PR TITLE
Remove nonsense

### PR DESCRIPTION
**Pull request by PascalBrouwers**
Remove nonsense about git setting to "avoid committing files by mistake"

### CODE REVIEW

**Comment by PascalBrouwers** [comment]
If you don't know what you are doing, don't put it in the readme as a suggestion.

**Comment by michaelyu0123** [comment]
Hello @PascalBrouwers, the reason for the inclusion of that suggestion is mainly for those that are concurrently working on development for both this extension as well as the root project in a local environment as composer.json/.lock will get updated by step 4 which sets the local directory as the source for the extension. 

By applying this suggestion, it prevents accidentally committing the change to pointing at local folder structure in the composer files up to the root projects repository.

Please let me know if the current phrasing was unclear or if there are other concerns with this and we'll do our best to address it. Thank you.

**Comment by PascalBrouwers** [comment]
So, you are saying people who develop this extension also have no idea what they are doing?
Ps. you can also use composer require with `--prefer-source` This allows you do be able to develop your extension with composer instead of doing these steps.

**Comment by supernova-at** [comment]
> you are saying people who develop this extension also have no idea what they are doing?

Hey @PascalBrouwers , comments like this are unnecessary and against the contributor code of conduct. If you have a better idea (such as using `--prefer-source`), please modify your PR to include that in the setup steps instead.

**Comment by PascalBrouwers** [comment]
Selectively quoting to make my sentence sound different is not appreciated. I think that is against the code of conduct.

**Pull request closed without merging**
